'use client';

//차후 개발 페이지
export default function CharacterBoard() {
  return (
    <section id='character_board_section' className='ml-2 w-1/2'>
      <ul
        style={{
          listStyle: 'none',
          display: 'grid',
          gridTemplateColumns: 'repeat(4, 1fr)',
          gap: '5px',
        }}
      >
        <li>
          <span>리시타</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_1.png'
            alt='리시타'
          />
        </li>
        <li>
          <span>피오나</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_2.png'
            alt='피오나'
          />
        </li>
        <li>
          <span>이비</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_3.png'
            alt='이비'
          />
        </li>
        <li>
          <span>카록</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_4.png'
            alt='카록'
          />
        </li>
        <li>
          <span>카이</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_5.png'
            alt='카이'
          />
        </li>
        <li>
          <span>벨라</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_6.png'
            alt='벨라'
          />
        </li>
        <li>
          <span>허크</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_7.png'
            alt='허크'
          />
        </li>
        <li>
          <span>린</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_8.png'
            alt='린'
          />
        </li>
        <li>
          <span>아리샤</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_9.png'
            alt='아리샤'
          />
        </li>
        <li>
          <span>헤기</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_10.png'
            alt='헤기'
          />
        </li>
        <li>
          <span>델리아</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_11.png'
            alt='델리아'
          />
        </li>
        <li>
          <span>미리</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_12.png'
            alt='미리'
          />
        </li>
        <li>
          <span>그림덴</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_13.png'
            alt='그림덴'
          />
        </li>
        <li>
          <span>미울</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_14.png'
            alt='미울'
          />
        </li>
        <li>
          <span>벨</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_15.png'
            alt='벨'
          />
        </li>
        <li>
          <span>레서</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_16.png'
            alt='레서'
          />
        </li>
        <li>
          <span>카엘</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_17.png'
            alt='카엘'
          />
        </li>
        <li>
          <span>테사</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_18.png'
            alt='테사'
          />
        </li>
        <li>
          <span>단아</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_19.png'
            alt='단아'
          />
        </li>
        <li>
          <span>레티</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_20.png'
            alt='레티'
          />
        </li>
        <li>
          <span>라티야</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_21.png'
            alt='라티야'
          />
        </li>
        <li>
          <span>체른</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_22.png'
            alt='체른'
          />
        </li>
        <li>
          <span>아켈</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_23.png'
            alt='아켈'
          />
        </li>
        <li>
          <span>소우</span>
          <img
            src='https://lwi.nexon.com/heroes/renewal/info/char_list_24.png'
            alt='소우'
          />
        </li>
      </ul>
    </section>
  );
}
